### ISSUE TITLE
Would be nice if MYSQL could be also installed... 

### ISSUE THREAD

**Issue by dwightmulcahy** [piku/deploy-gitea#4]
all in the title.

**Comment by chr15m** [comment]
I think the fix for this should be:

 * Create a `mysql.yml` playbook for the bootstrap script so the user can easily get mysql set up themselves.
 * Add a documentation note about using mysql, postgresql, or sqlite with this gitea deploy.

I'm using sqlite myself - I don't anticipate huge traffic on my gitea server.

**Comment by dwightmulcahy** [comment]
Agreed.  I've installed sqlite myself too.
